# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f727952cc613045479fc8d51db44845324e1b1d216378bd7e3d3ff5d6690e736cb71c0e8e5decbd1803207b2aabd15d3f92610be890b016e4b527ee89983ca9b

test:
  secret_key_base: d04537bc59ffb5c03f22276f64937873c302c6d9e67389e5c40546010b3c7f164c88e70184330a782cd361867690d90f42d3f8bde2c2e9c51c638f5519c0effe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
